/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ServicoReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "servico";
};

export type ObraReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "obra";
};

export type Depoimento = {
  _id: string;
  _type: "depoimento";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  nomeCliente?: string;
  cargoEmpresa?: string;
  foto?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  texto?: string;
  nota?: number;
  tipoServico?: ServicoReference;
  obraRelacionada?: ObraReference;
  destaque?: boolean;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Galeria = {
  _id: string;
  _type: "galeria";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titulo?: string;
  imagens?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
};

export type CategoriaVideoReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "categoriaVideo";
};

export type Video = {
  _id: string;
  _type: "video";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titulo?: string;
  slug?: Slug;
  url?: string;
  categoria?: CategoriaVideoReference;
  thumbnail?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  descricaoCurta?: string;
  descricaoCompleta?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  dataPublicacao?: string;
  duracao?: string;
  destaque?: boolean;
  obraRelacionada?: ObraReference;
  servicoRelacionado?: ServicoReference;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type CategoriaVideo = {
  _id: string;
  _type: "categoriaVideo";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  nome?: string;
  slug?: Slug;
};

export type MembroEquipe = {
  _id: string;
  _type: "membroEquipe";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  nome?: string;
  cargo?: string;
  foto?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: string;
  redesSociais?: Array<{
    rede?: "linkedin" | "instagram";
    url?: string;
    _key: string;
  }>;
  ordem?: number;
};

export type CategoriaReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "categoria";
};

export type Obra = {
  _id: string;
  _type: "obra";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titulo?: string;
  slug?: Slug;
  categoria?: CategoriaReference;
  tipoObra?: "construcao_nova" | "reforma" | "ampliacao" | "retrofit";
  status?: "em_andamento" | "concluida";
  servicosRealizados?: Array<string>;
  capa?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  galeria?: Array<{
    imagem?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    legenda?: string;
    etapa?: "antes" | "durante" | "depois";
    ordem?: number;
    _type: "itemGaleria";
    _key: string;
  }>;
  descricao?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  desafioObra?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  solucaoBezel?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  principaisServicos?: Array<string>;
  resultadosDestaques?: Array<string>;
  cliente?: string;
  exibirClientePublicamente?: boolean;
  area?: number;
  metragemTerreno?: number;
  metragemConstruida?: number;
  ano?: number;
  localizacao?: string;
  dataInicio?: string;
  dataConclusao?: string;
  previsaoConclusao?: string;
  prazoObra?: string;
  seo?: Seo;
};

export type Seo = {
  _type: "seo";
  metaTitulo?: string;
  metaDescricao?: string;
  imagemOg?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Projeto = {
  _id: string;
  _type: "projeto";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titulo?: string;
  slug?: Slug;
  categoria?: CategoriaReference;
  destaque?: boolean;
  capa?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  galeria?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  descricao?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  cliente?: string;
  area?: number;
  ano?: number;
  localizacao?: string;
  seo?: Seo;
};

export type Categoria = {
  _id: string;
  _type: "categoria";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  nome?: string;
  slug?: Slug;
};

export type Servico = {
  _id: string;
  _type: "servico";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titulo?: string;
  slug?: Slug;
  icone?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  descricaoCurta?: string;
  descricaoLonga?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  ordem?: number;
  seo?: Seo;
};

export type PoliticaPrivacidade = {
  _id: string;
  _type: "politicaPrivacidade";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titulo?: string;
  conteudo?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  seo?: Seo;
};

export type PaginaSobre = {
  _id: string;
  _type: "paginaSobre";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titulo?: string;
  textoIntroducao?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  imagemDestaque?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  missao?: string;
  visao?: string;
  valores?: Array<string>;
  tituloDiferenciais?: string;
  subtituloDiferenciais?: string;
  textoDiferenciais?: string;
  diferenciais?: Array<{
    titulo?: string;
    descricao?: string;
    _key: string;
  }>;
  mostrarEquipe?: boolean;
  seo?: Seo;
};

export type PaginaInicial = {
  _id: string;
  _type: "paginaInicial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  tituloHero?: string;
  subtituloHero?: string;
  imagemFundo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  textoCta?: string;
  linkCta?: string;
  tituloCtaFinal?: string;
  subtituloCtaFinal?: string;
  textoBotaoCtaFinal?: string;
  linkBotaoCtaFinal?: string;
  tituloGestao?: string;
  textoGestao?: string;
};

export type ConfiguracaoSite = {
  _id: string;
  _type: "configuracaoSite";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  nomeEmpresa?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  telefone?: string;
  whatsapp?: string;
  mensagemWhatsapp?: string;
  email?: string;
  endereco?: string;
  logradouro?: string;
  cidade?: string;
  estado?: string;
  cep?: string;
  cnpj?: string;
  regiaoAtendimento?: Array<string>;
  linkAvaliacoesGoogle?: string;
  instagramUrl?: string;
  facebookUrl?: string;
  youtubeUrl?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | ServicoReference
  | ObraReference
  | Depoimento
  | SanityImageCrop
  | SanityImageHotspot
  | Galeria
  | CategoriaVideoReference
  | Video
  | Slug
  | CategoriaVideo
  | MembroEquipe
  | CategoriaReference
  | Obra
  | Seo
  | Projeto
  | Categoria
  | Servico
  | PoliticaPrivacidade
  | PaginaSobre
  | PaginaInicial
  | ConfiguracaoSite
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/queries.ts
// Variable: configuracaoSiteQuery
// Query: *[_type == "configuracaoSite"][0]
export type ConfiguracaoSiteQueryResult = {
  _id: string;
  _type: "configuracaoSite";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  nomeEmpresa?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  telefone?: string;
  whatsapp?: string;
  mensagemWhatsapp?: string;
  email?: string;
  endereco?: string;
  logradouro?: string;
  cidade?: string;
  estado?: string;
  cep?: string;
  cnpj?: string;
  regiaoAtendimento?: Array<string>;
  linkAvaliacoesGoogle?: string;
  instagramUrl?: string;
  facebookUrl?: string;
  youtubeUrl?: string;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: paginaInicialQuery
// Query: *[_type == "paginaInicial"][0]
export type PaginaInicialQueryResult = {
  _id: string;
  _type: "paginaInicial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  tituloHero?: string;
  subtituloHero?: string;
  imagemFundo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  textoCta?: string;
  linkCta?: string;
  tituloCtaFinal?: string;
  subtituloCtaFinal?: string;
  textoBotaoCtaFinal?: string;
  linkBotaoCtaFinal?: string;
  tituloGestao?: string;
  textoGestao?: string;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: servicosQuery
// Query: *[_type == "servico"] | order(ordem asc)
export type ServicosQueryResult = Array<{
  _id: string;
  _type: "servico";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titulo?: string;
  slug?: Slug;
  icone?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  descricaoCurta?: string;
  descricaoLonga?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  ordem?: number;
  seo?: Seo;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: projetosDestaqueQuery
// Query: *[_type == "projeto" && destaque == true] | order(_createdAt desc)[0...6]{    _id,    titulo,    slug,    capa,    categoria->{nome}  }
export type ProjetosDestaqueQueryResult = Array<{
  _id: string;
  titulo: string | null;
  slug: Slug | null;
  capa: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  categoria: {
    nome: string | null;
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: paginaSobreQuery
// Query: *[_type == "paginaSobre"][0]
export type PaginaSobreQueryResult = {
  _id: string;
  _type: "paginaSobre";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titulo?: string;
  textoIntroducao?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  imagemDestaque?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  missao?: string;
  visao?: string;
  valores?: Array<string>;
  tituloDiferenciais?: string;
  subtituloDiferenciais?: string;
  textoDiferenciais?: string;
  diferenciais?: Array<{
    titulo?: string;
    descricao?: string;
    _key: string;
  }>;
  mostrarEquipe?: boolean;
  seo?: Seo;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: membrosEquipeQuery
// Query: *[_type == "membroEquipe"] | order(ordem asc)
export type MembrosEquipeQueryResult = Array<{
  _id: string;
  _type: "membroEquipe";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  nome?: string;
  cargo?: string;
  foto?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: string;
  redesSociais?: Array<{
    rede?: "instagram" | "linkedin";
    url?: string;
    _key: string;
  }>;
  ordem?: number;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: servicoBySlugQuery
// Query: *[_type == "servico" && slug.current == $slug][0]
export type ServicoBySlugQueryResult = {
  _id: string;
  _type: "servico";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titulo?: string;
  slug?: Slug;
  icone?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  descricaoCurta?: string;
  descricaoLonga?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  ordem?: number;
  seo?: Seo;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: servicoSlugsQuery
// Query: *[_type == "servico"]{ "slug": slug.current }
export type ServicoSlugsQueryResult = Array<{
  slug: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: projetosQuery
// Query: *[_type == "projeto"] | order(_createdAt desc){    _id, titulo, slug, capa, categoria->{nome}  }
export type ProjetosQueryResult = Array<{
  _id: string;
  titulo: string | null;
  slug: Slug | null;
  capa: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  categoria: {
    nome: string | null;
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: projetoBySlugQuery
// Query: *[_type == "projeto" && slug.current == $slug][0]{    ...,    categoria->{nome}  }
export type ProjetoBySlugQueryResult = {
  _id: string;
  _type: "projeto";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titulo?: string;
  slug?: Slug;
  categoria: {
    nome: string | null;
  } | null;
  destaque?: boolean;
  capa?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  galeria?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  descricao?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  cliente?: string;
  area?: number;
  ano?: number;
  localizacao?: string;
  seo?: Seo;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: projetoSlugsQuery
// Query: *[_type == "projeto"]{ "slug": slug.current }
export type ProjetoSlugsQueryResult = Array<{
  slug: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: obrasQuery
// Query: *[_type == "obra"] | order(_createdAt desc){    _id, titulo, slug, capa, status, categoria->{nome}  }
export type ObrasQueryResult = Array<{
  _id: string;
  titulo: string | null;
  slug: Slug | null;
  capa: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  status: "concluida" | "em_andamento" | null;
  categoria: {
    nome: string | null;
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: obraBySlugQuery
// Query: *[_type == "obra" && slug.current == $slug][0]{    ...,    categoria->{nome}  }
export type ObraBySlugQueryResult = {
  _id: string;
  _type: "obra";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titulo?: string;
  slug?: Slug;
  categoria: {
    nome: string | null;
  } | null;
  tipoObra?: "ampliacao" | "construcao_nova" | "reforma" | "retrofit";
  status?: "concluida" | "em_andamento";
  servicosRealizados?: Array<string>;
  capa?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  galeria?: Array<{
    imagem?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    legenda?: string;
    etapa?: "antes" | "depois" | "durante";
    ordem?: number;
    _type: "itemGaleria";
    _key: string;
  }>;
  descricao?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  desafioObra?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  solucaoBezel?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  principaisServicos?: Array<string>;
  resultadosDestaques?: Array<string>;
  cliente?: string;
  exibirClientePublicamente?: boolean;
  area?: number;
  metragemTerreno?: number;
  metragemConstruida?: number;
  ano?: number;
  localizacao?: string;
  dataInicio?: string;
  dataConclusao?: string;
  previsaoConclusao?: string;
  prazoObra?: string;
  seo?: Seo;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: obraSlugsQuery
// Query: *[_type == "obra"]{ "slug": slug.current }
export type ObraSlugsQueryResult = Array<{
  slug: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: videosQuery
// Query: *[_type == "video"] | order(    coalesce(dataPublicacao, "0000-00-00") desc  ){    _id,    titulo,    slug,    url,    thumbnail,    descricaoCurta,    descricaoCompleta,    dataPublicacao,    duracao,    destaque,    categoria->{_id, nome}  }
export type VideosQueryResult = Array<{
  _id: string;
  titulo: string | null;
  slug: Slug | null;
  url: string | null;
  thumbnail: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  descricaoCurta: string | null;
  descricaoCompleta: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  dataPublicacao: string | null;
  duracao: string | null;
  destaque: boolean | null;
  categoria: {
    _id: string;
    nome: string | null;
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: depoimentosQuery
// Query: *[_type == "depoimento"] | order(_createdAt desc){    _id,    nomeCliente,    cargoEmpresa,    foto,    texto,    nota,    tipoServico->{nome},    obraRelacionada->{titulo, "slug": slug.current}  }
export type DepoimentosQueryResult = Array<{
  _id: string;
  nomeCliente: string | null;
  cargoEmpresa: string | null;
  foto: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  texto: string | null;
  nota: number | null;
  tipoServico: {
    nome: null;
  } | null;
  obraRelacionada: {
    titulo: string | null;
    slug: string | null;
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: politicaPrivacidadeQuery
// Query: *[_type == "politicaPrivacidade"][0]
export type PoliticaPrivacidadeQueryResult = {
  _id: string;
  _type: "politicaPrivacidade";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titulo?: string;
  conteudo?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  seo?: Seo;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: categoriasVideoUsadasQuery
// Query: *[_type == "categoriaVideo" && count(*[_type == "video" && references(^._id)]) > 0]{    _id,    nome  }
export type CategoriasVideoUsadasQueryResult = Array<{
  _id: string;
  nome: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: depoimentosDestaqueQuery
// Query: *[_type == "depoimento" && destaque == true] | order(_createdAt desc)[0...3]{    _id,    nomeCliente,    cargoEmpresa,    foto,    texto,    nota,    tipoServico->{nome},    obraRelacionada->{titulo, "slug": slug.current}  }
export type DepoimentosDestaqueQueryResult = Array<{
  _id: string;
  nomeCliente: string | null;
  cargoEmpresa: string | null;
  foto: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  texto: string | null;
  nota: number | null;
  tipoServico: {
    nome: null;
  } | null;
  obraRelacionada: {
    titulo: string | null;
    slug: string | null;
  } | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "configuracaoSite"][0]': ConfiguracaoSiteQueryResult;
    '*[_type == "paginaInicial"][0]': PaginaInicialQueryResult;
    '*[_type == "servico"] | order(ordem asc)': ServicosQueryResult;
    '*[_type == "projeto" && destaque == true] | order(_createdAt desc)[0...6]{\n    _id,\n    titulo,\n    slug,\n    capa,\n    categoria->{nome}\n  }': ProjetosDestaqueQueryResult;
    '*[_type == "paginaSobre"][0]': PaginaSobreQueryResult;
    '*[_type == "membroEquipe"] | order(ordem asc)': MembrosEquipeQueryResult;
    '*[_type == "servico" && slug.current == $slug][0]': ServicoBySlugQueryResult;
    '*[_type == "servico"]{ "slug": slug.current }': ServicoSlugsQueryResult;
    '*[_type == "projeto"] | order(_createdAt desc){\n    _id, titulo, slug, capa, categoria->{nome}\n  }': ProjetosQueryResult;
    '*[_type == "projeto" && slug.current == $slug][0]{\n    ...,\n    categoria->{nome}\n  }': ProjetoBySlugQueryResult;
    '*[_type == "projeto"]{ "slug": slug.current }': ProjetoSlugsQueryResult;
    '*[_type == "obra"] | order(_createdAt desc){\n    _id, titulo, slug, capa, status, categoria->{nome}\n  }': ObrasQueryResult;
    '*[_type == "obra" && slug.current == $slug][0]{\n    ...,\n    categoria->{nome}\n  }': ObraBySlugQueryResult;
    '*[_type == "obra"]{ "slug": slug.current }': ObraSlugsQueryResult;
    '*[_type == "video"] | order(\n    coalesce(dataPublicacao, "0000-00-00") desc\n  ){\n    _id,\n    titulo,\n    slug,\n    url,\n    thumbnail,\n    descricaoCurta,\n    descricaoCompleta,\n    dataPublicacao,\n    duracao,\n    destaque,\n    categoria->{_id, nome}\n  }': VideosQueryResult;
    '*[_type == "depoimento"] | order(_createdAt desc){\n    _id,\n    nomeCliente,\n    cargoEmpresa,\n    foto,\n    texto,\n    nota,\n    tipoServico->{nome},\n    obraRelacionada->{titulo, "slug": slug.current}\n  }': DepoimentosQueryResult;
    '*[_type == "politicaPrivacidade"][0]': PoliticaPrivacidadeQueryResult;
    '*[_type == "categoriaVideo" && count(*[_type == "video" && references(^._id)]) > 0]{\n    _id,\n    nome\n  }': CategoriasVideoUsadasQueryResult;
    '*[_type == "depoimento" && destaque == true] | order(_createdAt desc)[0...3]{\n    _id,\n    nomeCliente,\n    cargoEmpresa,\n    foto,\n    texto,\n    nota,\n    tipoServico->{nome},\n    obraRelacionada->{titulo, "slug": slug.current}\n  }': DepoimentosDestaqueQueryResult;
  }
}
